#include <cstdlib>

#include "geometry/types.hpp"
#include <iomanip>
#include <iostream>
#include <stdexcept>
#include <string>
#include <string_view>

namespace {

using shiny::nfp::geom::Point2;
using shiny::nfp::geom::PolygonWithHoles;

auto parse_double(const char *value, std::string_view label) -> double {
  char *end = nullptr;
  const double parsed = std::strtod(value, &end);
  if (end == value || (end != nullptr && *end != '\0')) {
    throw std::runtime_error("invalid numeric value for " + std::string(label));
  }
  return parsed;
}

auto make_rectangle(double min_x, double min_y, double max_x, double max_y)
    -> PolygonWithHoles {
  return {
      .outer =
          {
              {.x = min_x, .y = min_y},
              {.x = max_x, .y = min_y},
              {.x = max_x, .y = max_y},
              {.x = min_x, .y = max_y},
          },
  };
}

auto make_polygon_from_args(int start_index, int argc, char **argv)
    -> PolygonWithHoles {
  const int coordinate_count = argc - start_index;
  if (coordinate_count < 6 || coordinate_count % 2 != 0) {
    throw std::runtime_error(
        "polygon mode expects x y coordinate pairs for at least three points");
  }

  PolygonWithHoles polygon;
  for (int index = start_index; index < argc; index += 2) {
    polygon.outer.push_back(Point2{parse_double(argv[index], "x"),
                                   parse_double(argv[index + 1], "y")});
  }
  return polygon;
}

void write_polygon(std::ostream &stream, const PolygonWithHoles &polygon,
                   int indent) {
  const std::string pad(static_cast<std::size_t>(indent), ' ');
  const std::string child_pad(static_cast<std::size_t>(indent + 2), ' ');
  const std::string point_pad(static_cast<std::size_t>(indent + 4), ' ');

  stream << pad << "{\n";
  stream << child_pad << "\"outer\": [\n";
  for (std::size_t index = 0; index < polygon.outer.size(); ++index) {
    const auto &point = polygon.outer[index];
    stream << point_pad << '[' << std::fixed << std::setprecision(6) << point.x
           << ", " << point.y << ']';
    if (index + 1U < polygon.outer.size()) {
      stream << ',';
    }
    stream << '\n';
  }
  stream << child_pad << "],\n";
  stream << child_pad << "\"holes\": []\n";
  stream << pad << '}';
}

void print_usage() {
  std::cerr << "usage:\n"
            << "  shiny_nfp_engine_fixture_gen rectangle <min_x> <min_y> "
               "<max_x> <max_y>\n"
            << "  shiny_nfp_engine_fixture_gen polygon <x1> <y1> <x2> <y2> "
               "<x3> <y3> [...]\n"
            << "  shiny_nfp_engine_fixture_gen fixture-rectangle <id> <kind> "
               "<min_x> <min_y> <max_x> <max_y>\n"
            << "  shiny_nfp_engine_fixture_gen fixture-polygon <id> <kind> "
               "<x1> <y1> <x2> <y2> <x3> <y3> [...]\n"
            << "  shiny_nfp_engine_fixture_gen contract-rectangle <id> <kind> "
               "<input_key> <min_x> <min_y> <max_x> <max_y>\n"
            << "  shiny_nfp_engine_fixture_gen contract-polygon <id> <kind> "
               "<input_key> <x1> <y1> <x2> <y2> <x3> <y3> [...]\n";
}

void write_fixture_envelope(std::ostream &stream, std::string_view id,
                            std::string_view kind,
                            const PolygonWithHoles &polygon) {
  stream << "{\n";
  stream << "  \"id\": \"" << id << "\",\n";
  stream << "  \"kind\": \"" << kind << "\",\n";
  stream << "  \"polygon\":\n";
  write_polygon(stream, polygon, 2);
  stream << "\n}\n";
}

void write_fixture_contract(std::ostream &stream, std::string_view id,
                            std::string_view kind, std::string_view input_key,
                            const PolygonWithHoles &polygon) {
  stream << "{\n";
  stream << "  \"id\": \"" << id << "\",\n";
  stream << "  \"kind\": \"" << kind << "\",\n";
  stream << "  \"normative\": true,\n";
  stream << "  \"source\": \"generated\",\n";
  stream << "  \"inputs\": {\n";
  stream << "    \"" << input_key << "\":\n";
  write_polygon(stream, polygon, 6);
  stream << "\n  },\n";
  stream << "  \"expected\": {},\n";
  stream << "  \"notes\": \"generated by shiny_nfp_engine_fixture_gen\"\n";
  stream << "}\n";
}

} // namespace

auto main(int argc, char **argv) -> int {
  try {
    if (argc < 2) {
      print_usage();
      return 1;
    }

    const std::string_view mode{argv[1]};

    if (mode == "rectangle") {
      if (argc != 6) {
        print_usage();
        return 1;
      }

      const auto polygon = make_rectangle(
          parse_double(argv[2], "min_x"), parse_double(argv[3], "min_y"),
          parse_double(argv[4], "max_x"), parse_double(argv[5], "max_y"));
      write_polygon(std::cout, polygon, 0);
      std::cout << '\n';
      return 0;
    }

    if (mode == "polygon") {
      const auto polygon = make_polygon_from_args(2, argc, argv);
      write_polygon(std::cout, polygon, 0);
      std::cout << '\n';
      return 0;
    }

    if (mode == "fixture-rectangle") {
      if (argc != 8) {
        print_usage();
        return 1;
      }

      const auto polygon = make_rectangle(
          parse_double(argv[4], "min_x"), parse_double(argv[5], "min_y"),
          parse_double(argv[6], "max_x"), parse_double(argv[7], "max_y"));
      write_fixture_envelope(std::cout, argv[2], argv[3], polygon);
      return 0;
    }

    if (mode == "fixture-polygon") {
      if (argc < 10) {
        print_usage();
        return 1;
      }

      const auto polygon = make_polygon_from_args(4, argc, argv);
      write_fixture_envelope(std::cout, argv[2], argv[3], polygon);
      return 0;
    }

    if (mode == "contract-rectangle") {
      if (argc != 9) {
        print_usage();
        return 1;
      }

      const auto polygon = make_rectangle(
          parse_double(argv[5], "min_x"), parse_double(argv[6], "min_y"),
          parse_double(argv[7], "max_x"), parse_double(argv[8], "max_y"));
      write_fixture_contract(std::cout, argv[2], argv[3], argv[4], polygon);
      return 0;
    }

    if (mode == "contract-polygon") {
      if (argc < 11) {
        print_usage();
        return 1;
      }

      const auto polygon = make_polygon_from_args(5, argc, argv);
      write_fixture_contract(std::cout, argv[2], argv[3], argv[4], polygon);
      return 0;
    }

    print_usage();
    return 1;
  } catch (const std::exception &error) {
    std::cerr << error.what() << '\n';
    return 1;
  }
}